/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 49f5f50319cd9ca9d73a31225fb78235)
// Runtime types generated with workerd@1.20251210.0 2025-10-08 
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Hono/CF";
		DB: D1Database;
    STRIPE_SECRET_KEY: string;
    FRONTEND_URL: string;
	}
}
interface Env extends Cloudflare.Env {}
